//---------------------------------------------------------------------
// This class should be auto-generated by data schema
// This can be used to simplise development when doing extended development by users(client)
//---------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Zendesk.JsonSearch.Models.EarlyBound
{
    public class Ticket : Entity
    {
        public Ticket() : base() { }
        public Ticket(string id, string logicName) : base(id, logicName)
        { }
        public DateTime? created_at
        {
            get => DateTime.Parse(GetAttribute<string>(nameof(created_at)));
            set => SetAttribute(nameof(created_at), value);
        }
        public string type
        {
            get => GetAttribute<string>(nameof(type));
            set => SetAttribute(nameof(type), value);
        }
        public string subject
        {
            get => GetAttribute<string>(nameof(subject));
            set => SetAttribute(nameof(subject), value);
        }
        public EntityReference assignee
        {
            get => GetAttribute<EntityReference>(nameof(assignee));
            set => SetAttribute(nameof(assignee), value);
        }
        public List<string> tags
        {
            get => GetAttribute<List<string>>(nameof(tags));
            set => SetAttribute(nameof(tags), value);
        }
    }
}
