//---------------------------------------------------------------------
// This class should be auto-generated by data schema
// This can be used to simplise development when doing extended development by users(client)
//---------------------------------------------------------------------


using System;

namespace Zendesk.JsonSearch.Models.EarlyBound
{
    public class User : Entity
    {
        public User() : base() { }
        public User(string id, string logicName) : base(id, logicName)
        { }
        public DateTime created_at
        {
            get => DateTime.Parse(GetAttribute<string>(nameof(created_at)));
            set => this.SetAttribute(nameof(created_at), value);
        }
        public bool? verified
        {
            get => this.GetAttribute<bool>(nameof(verified));
            set => this.SetAttribute(nameof(verified), value);
        }
    }
}
